type = 'Ranged'

#Weapon Details
[weapon]
name = 'Gravity Gun'
flavor_text = 'The Power of Z'

#Technical Specifications
[attack_info]
attach_point = 'left hand'
ammo = 1
attack_template = 'cylinder'
projectile_spawn_location = 10 #grids in front of you
attack_radius = [5, 10, 50] # height and width 
can_move = true
invulnerable_during = false
terrain_destructor = true
projectile_dmg = 50
collision_dmg = 0

[effects]
particle_effect = ''
sfx_on_use = true #with/without text to voice
sfx = 'Beyooooooooooo'

#Timing
[timing] 
telegraph_time = 1 #1st step, time in seconds
attack_duration = 3