type = 'Ranged'
default = 'idle'
size = 0.1
rotation = [0, 0, 0]
position = [0, 40, 40]

[animation.idle]
    time = 100000
    vox = [
        "weapons/bolter.vox"
    ]

[ammo]
    default = "idle"
    size = 0.1
    speed = 5
    spread = 100
    ttl = 1000
    rate = 100
    rotation = [0, -90, -90]
    position = [0, 30, -20]

[ammo.animation.idle]
    speed = 1000
    vox = [
        "Weapons/meteor/meteorv3-00.vox",
        "Weapons/meteor/meteorv3-01.vox",
        "Weapons/meteor/meteorv3-02.vox",
        "Weapons/meteor/meteorv3-03.vox",
        "Weapons/meteor/meteorv3-04.vox",
    ]

#Weapon Details
[weapon]
name = 'Meteor'
flavor_text = 'Probably not a good idea.'
model = ''

#Technical Specifications

[attack_info]
attach_point = 'right hand'
ammo = 20
attack_template = 'square'
projectile_spawn_location = [2, 100] #grids in front of you, grids above you
bullet_size = [1, 1, 1]
attack_radius = [15, 15, 15] # height and width 
can_move = false
can_charge = false
invulnerable_during = false
terrain_destructor = true
projectile_dmg = 75
collision_dmg = 75
velocity = 10 #meters per second? 

[effects]
particle_effect = 'meteor'
sfx_on_use = true #with/without text to voice
sfx = 'fire trailing' 

#Timing
[timing] 
telegraph_time = 5 #1st step, time in seconds
attack_duration = 7
